# hotel_api_project/docker-compose.yml

services:
  # Servicio de la aplicaci√≥n Django (Backend)
  web:
    build: .
    container_name: hotel_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: hotel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # üö® NUEVO SERVICIO: pgAdmin (Interfaz gr√°fica para la DB)
  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel_pgadmin
    environment:
      # Credenciales de login para acceder a pgAdmin en el navegador
      PGADMIN_DEFAULT_EMAIL: admin@hotelapi.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password # Usa una contrase√±a segura!
    ports:
      - "5050:80" # Mapeamos el puerto interno 80 al puerto 5050 de tu host
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db # Asegura que la DB est√© lista para que pgAdmin se conecte

volumes:
  postgres_data:
  pgadmin_data: # Nuevo volumen para persistir la configuraci√≥n de pgAdmin
